  Parameters:
    IndoorNavVpcID:
      Type: String
      Description: VPC identifier

  Resources:
    IndoorNavNetworkAcl:
      Type: 'AWS::EC2::NetworkAcl'
      Properties:
        VpcId: !Ref IndoorNavVpcID
        Tags:
          - Key: Name
            Value: Indoor-Nav-NetworkAcl
            
    IngressRule100:
      Type: 'AWS::EC2::NetworkAclEntry'
      Properties:
        NetworkAclId: !Ref IndoorNavNetworkAcl
        RuleNumber: 100
        Protocol: -1
        CidrBlock: 0.0.0.0/0
        Egress: false
        RuleAction: allow
          
    EgressRule100:
      Type: 'AWS::EC2::NetworkAclEntry'
      Properties:
        NetworkAclId: !Ref IndoorNavNetworkAcl
        RuleNumber: 100
        Protocol: -1
        CidrBlock: 0.0.0.0/0
        Egress: true
        RuleAction: allow

  Outputs:
    IndoorNavNetworkAclID:
      Value: !Ref IndoorNavNetworkAcl
      Description: Network Access Control List identifier
    